import {identifier,jobIdentifier,filters,applicationPatch,resumeText,userCredentials,invalid} from './validation.mjs';
import {writeRunEventStream} from './event-stream.mjs';import {extractResumeText} from '../resume/extract-text.mjs';import {analyzeResumeOffline} from '../resume/offline.mjs';import {normalizeProfile,analyzeResume} from '../resume/profile.mjs';import {createModelBudget} from '../llm/budget.mjs';import {redactBusiness} from '../domain/redact.mjs';
const decode=value=>{try{return decodeURIComponent(value);}catch{invalid('Invalid encoded path');}};
export async function handleV2Request(req,res,context){
 const url=new URL(req.url,'http://localhost'),pathname=url.pathname;if(!pathname.startsWith('/api/v2/'))return false;const route=pathname.slice(7),method=req.method;const {http,workspaceService:workspace,jobService:jobs,runService:runs}=context;const send=(status,data)=>http.json(req,res,status,data),body=()=>http.readJson(req);let match;
 if(route==='/profiles/import-preview'&&method==='POST'){const input=await body();let text=input.resumeText||input.text,warnings=[],format='text';if(input.base64){const extracted=await extractResumeText(Buffer.from(String(input.base64).replace(/^data:[^;]+;base64,/,''),'base64'),String(input.filename||'resume.txt'));text=extracted.text;warnings=extracted.warnings||[];format=extracted.format;}text=resumeText(text);let profile=normalizeProfile(analyzeResumeOffline(text));if(input.mode==='ai'){const client=context.modelFactory({budget:createModelBudget(),credentials:userCredentials(input,context.cfg)});if(client.available)try{profile=await analyzeResume(client,text);}catch{warnings.push('模型提取失败，使用离线预览。');}else warnings.push('未配置模型密钥，使用离线预览。');}send(200,{text,profile:{...profile,education:profile.degree,cities:profile.preferredCities,explicitFacts:{}},format,warnings,inferred:true,parserVersion:'preview-2'});return true;}
 if(route==='/profiles'){if(method==='GET')send(200,{profiles:await workspace.listProfiles()});else if(method==='POST'){const input=await body();if(input.profileId)identifier(input.profileId);send(201,await workspace.saveProfile(redactBusiness(input)));}else return false;return true;}
 if((match=route.match(/^\/profiles\/([^/]+)\/revisions(?:\/([^/]+))?$/))){const id=identifier(decode(match[1])),revision=match[2]?decode(match[2]):null;const revisionId=revision?(revision.includes('@')?identifier(revision,{revision:true}):identifier(id+'@'+revision,{revision:true})):null;if(method==='POST'&&!revisionId)send(201,await workspace.saveProfile({...redactBusiness(await body()),profileId:id}));else if(method==='GET'){const revisions=(await workspace.listProfiles()).filter(p=>p.profileId===id);if(revisionId){const found=revisions.find(p=>p.revisionId===revisionId);if(!found)invalid('Profile revision not found',404);send(200,found);}else send(200,{revisions});}else if(method==='DELETE'&&revisionId)send(200,await workspace.deleteProfileRevision(revisionId));else return false;return true;}
 if(route==='/targets'){if(method==='GET')send(200,{targets:await workspace.listTargets()});else if(method==='POST'){const input=await body();if(input.targetId)identifier(input.targetId);identifier(input.profileRevisionId,{revision:true});send(201,await workspace.saveTarget(input));}else return false;return true;}
 if((match=route.match(/^\/targets\/([^/]+)$/))&&['PUT','PATCH'].includes(method)){const id=identifier(decode(match[1])),previous=(await workspace.listTargets()).filter(t=>t.targetId===id).at(-1);if(!previous)invalid('Target not found',404);const input=await body();if(input.profileRevisionId)identifier(input.profileRevisionId,{revision:true});send(200,await workspace.saveTarget({...previous,...input,targetId:id}));return true;}
 if(route==='/runs'){if(method==='GET')send(200,{runs:await runs.listRuns({status:url.searchParams.get('status')||undefined,targetId:url.searchParams.get('targetId')||undefined})});else if(method==='POST'){const input=await body();identifier(input.targetRevisionId,{revision:true});send(202,await runs.startRun({targetRevisionId:input.targetRevisionId,mode:input.mode||'rules',credentials:{...userCredentials(input,context.cfg),ip:http.ip(req)}}));}else return false;return true;}
 if((match=route.match(/^\/runs\/([^/]+)(?:\/(events|cancel))?$/))){const id=identifier(decode(match[1]));if(match[2]==='events'&&method==='GET'){const raw=url.searchParams.get('afterSeq')||'0';if(!/^\d+$/.test(raw)||!Number.isSafeInteger(Number(raw)))invalid('Invalid event cursor');await writeRunEventStream({req,res,runId:id,afterSeq:Number(raw),eventHub:context.eventHub});}else if(match[2]==='cancel'&&method==='POST')send(200,await runs.cancelRun(id));else if(!match[2]&&method==='GET')send(200,await runs.getRun(id));else return false;return true;}
 if(route==='/jobs/evaluations'&&method==='POST'){const input=await body();identifier(input.profileRevisionId,{revision:true});identifier(input.targetRevisionId,{revision:true});if(!Array.isArray(input.jobIds)||input.jobIds.length>5000)invalid('Invalid job ids (maximum5000)');input.jobIds.forEach(jobIdentifier);const credentials=userCredentials(input,context.cfg),client=['ai','auto'].includes(input.mode)?context.modelFactory({credentials,budget:createModelBudget()}):undefined;send(200,await context.evaluationService.rescore({...input,mode:input.mode||'rules',modelClient:client}));return true;}
 if(route==='/jobs'&&method==='GET'){send(200,await jobs.queryJobs(filters(url.searchParams)));return true;}
 if((match=route.match(/^\/jobs\/([^/]+)(?:\/(evaluations|application|links))?$/))){const id=jobIdentifier(decode(match[1]));if(!match[2]&&method==='GET')send(200,await jobs.getJob(id));else if(match[2]==='application'&&['POST','PUT'].includes(method))send(200,await jobs.updateApplication(id,applicationPatch(await body())));else if(match[2]==='evaluations'&&method==='POST'){const input=await body();identifier(input.profileRevisionId,{revision:true});identifier(input.targetRevisionId,{revision:true});const credentials=userCredentials(input,context.cfg),client=input.mode==='ai'?context.modelFactory({credentials,budget:createModelBudget()}):undefined;send(200,await context.evaluationService.rescore({jobIds:[id],profileRevisionId:input.profileRevisionId,targetRevisionId:input.targetRevisionId,mode:input.mode||'rules',modelClient:client}));}else if(match[2]==='links'&&['POST','DELETE'].includes(method)){const input=await body(),other=jobIdentifier(input.jobId);send(200,await (method==='POST'?jobs.linkJobs(id,other):jobs.unlinkJobs(id,other)));}else return false;return true;}
 if((match=route.match(/^\/applications\/([^/]+)$/))&&method==='PUT'){send(200,await jobs.updateApplication(jobIdentifier(decode(match[1])),applicationPatch(await body())));return true;}
 if(route==='/sources'&&method==='GET'){send(200,{sources:await context.sourceService.listSources(),sites:await context.getCatalog()});return true;}
 if(route==='/sources/sites'&&method==='POST'){const input=await body();identifier(input.siteId);identifier(input.providerId);send(201,await context.sourceService.addSite(input));return true;}
 if((match=route.match(/^\/sources\/([^/]+)\/(probe|settings)$/))&&['POST','PUT'].includes(method)){const id=identifier(decode(match[1])),input=await body();if(input.siteId)identifier(input.siteId);send(200,match[2]==='probe'?await context.sourceService.probe(id,input.siteId):await context.sourceService.saveSourceConfig({sourceId:id,config:input.config||input}));return true;}
 if(route==='/settings'){if(method==='GET')send(200,await context.getSettings());else if(['POST','PUT'].includes(method))send(200,await context.saveSettings(await body()));else return false;return true;}
 if(route==='/imports'&&method==='POST'){send(201,await context.importService.import(await body()));return true;}
 if(route==='/exports'&&['POST','GET'].includes(method)){const input=method==='POST'?await body():{format:url.searchParams.get('format')||'json',filters:filters(url.searchParams)},result=await context.exportService.export(input);res.writeHead(200,{'Content-Type':result.contentType,'Content-Disposition':'attachment; filename="'+result.filename+'"','Cache-Control':'no-store'});res.end(result.body);return true;}
 if(route==='/workspace/backup'&&['POST','GET'].includes(method)){send(200,await context.backup());return true;}
 if(route==='/workspace/restore'&&method==='POST'){send(200,await context.restore((await body()).archive));return true;}
 return false;
}
