import http from 'node:http';import https from 'node:https';
import {resolvePublicUrl,validatePublicUrl,isPublicAddress} from './public-url.mjs';import {createSourceBudget} from './budget.mjs';import {sharedScheduler,cancellableSleep,abortError} from './scheduler.mjs';import {createResponseCache} from './cache.mjs';
export function socketTransport({url,addresses,method='GET',headers={},body,signal,maxBytes}) {return new Promise((resolve,reject)=>{
 const address=addresses[0];const request=(url.protocol==='https:'?https:http).request(url,{method,headers,signal,agent:false,lookup:(host,options,callback)=>options.all?callback(null,[address]):callback(null,address.address,address.family)},res=>{const chunks=[];let size=0;res.on('data',chunk=>{size+=chunk.length;if(size>maxBytes){request.destroy(Error('Response size limit exceeded'));return;}chunks.push(chunk);});res.on('error',reject);res.on('end',()=>{const content=Buffer.concat(chunks);const charset=String(res.headers['content-type']||'').match(/charset\s*=\s*([^;\s]+)/i)?.[1]||'utf-8';let text;try{text=new TextDecoder(charset).decode(content);}catch{text=content.toString('utf8');}resolve({status:res.statusCode,headers:Object.fromEntries(Object.entries(res.headers).map(([k,v])=>[k,Array.isArray(v)?v.join(','):String(v||'')])),text,url:url.href});});});
 request.on('error',reject);request.on('socket',socket=>{const connected=()=>{if(!isPublicAddress(socket.remoteAddress)||!addresses.some(a=>a.address===socket.remoteAddress||a.family===4&&socket.remoteAddress==='::ffff:'+a.address)){request.destroy(Error('Unexpected connected address'));return;}request.end(body);};socket.once(url.protocol==='https:'?'secureConnect':'connect',connected);});
 });}
function abortable(promise,signal){signal?.throwIfAborted();return new Promise((resolve,reject)=>{const abort=()=>reject(abortError(signal));signal?.addEventListener('abort',abort,{once:true});Promise.resolve(promise).then(resolve,reject).finally(()=>signal?.removeEventListener('abort',abort));});}
export function createRequestClient({scheduler=sharedScheduler,budget=createSourceBudget(),transport=socketTransport,dnsLookup,cache=createResponseCache(),clock={now:Date.now,sleep:cancellableSleep},signal:defaultSignal,maxBytes=4*1024*1024}={}) {
 return async function request(value,options={}){const signal=options.signal&&defaultSignal?AbortSignal.any([options.signal,defaultSignal]):options.signal||defaultSignal;signal?.throwIfAborted();let url=validatePublicUrl(value);for(const key of Object.keys(options.headers||{}))if(['host',':authority'].includes(key.toLowerCase()))throw Error('Host override forbidden');
 const cacheKey=options.cacheKey?JSON.stringify([url.href,options.method||'GET',options.cacheKey]):null;const cached=cacheKey&&cache.get(cacheKey);if(cached)return cached;let retries=0,redirects=0;let method=options.method||'GET',body=options.body,headers={...options.headers};
 for(;;){signal?.throwIfAborted();let response;try{response=await scheduler.run(url.origin,async()=>{signal?.throwIfAborted();const timed=AbortSignal.timeout(options.timeoutMs??15000);const combined=signal?AbortSignal.any([signal,timed]):timed;const resolved=await abortable(resolvePublicUrl(url,{dnsLookup}),combined);combined.throwIfAborted();budget.claimRequest(redirects?'redirect':retries?'retry':options.kind||'request');const result=await abortable(transport({...resolved,method,headers,body,signal:combined,maxBytes}),combined);if(Buffer.byteLength(result.text||'')>maxBytes)throw Error('Response size limit exceeded');return {...result,url:result.url||url.href,headers:Object.fromEntries(Object.entries(result.headers||{}).map(([k,v])=>[k.toLowerCase(),String(v)]))};},{signal,minIntervalMs:options.minIntervalMs||0});}
 catch(e){if(signal?.aborted)throw abortError(signal);if(retries<2&&['ECONNRESET','ETIMEDOUT','EAI_AGAIN','ECONNREFUSED'].includes(e.code)){retries++;await clock.sleep(400*2**(retries-1),signal);continue;}throw e;}
 if([301,302,303,307,308].includes(response.status)&&response.headers.location){if(++redirects>3)throw Error('Redirect limit exceeded');const next=validatePublicUrl(new URL(response.headers.location,url).href);if(next.origin!==url.origin){if(body!==undefined&&[307,308].includes(response.status))throw Error('Cross-origin body redirect forbidden');headers=Object.fromEntries(Object.entries(headers).filter(([k])=>!['authorization','cookie','proxy-authorization','x-api-key'].includes(k.toLowerCase())));}if(response.status===303||[301,302].includes(response.status)&&method==='POST'){method='GET';body=undefined;}url=next;continue;}
 if((response.status===429||response.status>=500)&&retries<2){retries++;const ra=response.headers['retry-after'];const delay=ra?(Number.isFinite(Number(ra))?Number(ra)*1000:Date.parse(ra)-clock.now()):400*2**(retries-1);await clock.sleep(Math.max(0,Math.min(60000,delay||400)),signal);continue;}
 if(cacheKey&&response.status===200)cache.set(cacheKey,response);return response;}
 };
}
