import test from 'node:test';
import assert from 'node:assert/strict';
import {packageBusinessFixture} from '../helpers/package-business-fixture.mjs';
import {seedUnassignedClosure} from '../helpers/legacy-business-fixture.mjs';
import {createLegacyAssignmentService,applyOwnershipTransfer} from '../../src/application/legacy-assignment-service.mjs';
import {createPurgeService} from '../../src/application/purge-service.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
async function fixture(t,options){const f=await packageBusinessFixture(t);Object.assign(f,await f.twoTargets());Object.assign(f,await seedUnassignedClosure(f,options));let failureAfterPrepare=false;const repository={...f.repository,withMaintenanceTransaction(action,opts){return f.repository.withMaintenanceTransaction(tx=>action({...tx,async commitControl(next){await tx.commitControl(next);if(failureAfterPrepare&&Object.values(next.ownershipTransfers).some(i=>i.phase==='prepared')){failureAfterPrepare=false;f.armFailure('workspace_commit');}this.control=tx.control;},async commitWorkspace(next){const result=await tx.commitWorkspace(next);this.workspace=tx.workspace;return result;}}),opts);}};f.assignment=createLegacyAssignmentService({repository,operationGate:f.operationGate});f.failTransferMain=()=>{failureAfterPrepare=true;};return f;}
test('assignment moves one complete closure with original identities and target facts',async t=>{
 const f=await fixture(t),p=await f.assignment.preview({recordId:f.recordId,destination:f.a});assert.ok(p.recordIds.length>=6);const before=await f.repository.read();const result=await f.assignment.move({...p,recordId:f.recordId,destination:f.a});const w=await f.repository.read();assert.equal(result.ownerPackageId,f.a.packageId);assert.equal((await f.assignment.list()).length,0);assert.equal(w.applications[f.applicationId].recordId,f.recordId);assert.equal(w.applications[f.applicationId].events[0].recordId,before.applications[f.applicationId].events[0].recordId);assert.equal(w.jobs[f.jobId].ownerPackageId,f.a.packageId);assert.equal(w.targetMembers[f.a.targetRevisionId][f.jobId].factRefs[0].observationId,f.observationId);assert.equal((await f.control.read()).ownershipTransfers[f.recordId].to,f.a.packageId);await assert.rejects(()=>f.jobs.getApplication(f.applicationId,f.b),{code:'package_scope_mismatch'});
});
test('concurrent assignment has only one success and never duplicates bodies',async t=>{
 const f=await fixture(t),p=await f.assignment.preview({recordId:f.recordId,destination:f.a});const results=await Promise.allSettled([f.assignment.move({...p,recordId:f.recordId,destination:f.a}),f.assignment.move({...p,recordId:f.recordId,destination:f.a})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(Object.values((await f.repository.read()).applications).filter(a=>a.recordId===f.recordId).length,1);
});
test('control intent survives failed main commit and blocks a second destination until recovery',async t=>{
 const f=await fixture(t),p=await f.assignment.preview({recordId:f.recordId,destination:f.a});f.failTransferMain();await assert.rejects(()=>f.assignment.move({...p,recordId:f.recordId,destination:f.a}));assert.equal((await f.control.read()).ownershipTransfers[f.recordId].phase,'prepared');await assert.rejects(()=>f.assignment.preview({recordId:f.recordId,destination:f.b}),{code:'ownership_transfer_pending'});await f.assignment.recoverPending();const w=await f.repository.read();assert.equal(w.applications[f.applicationId].ownerPackageId,f.a.packageId);assert.equal((await f.control.read()).ownershipTransfers[f.recordId].phase,'complete');assert.equal(Object.keys(w.applications).length,1);
});
test('unknown target/image dependency is rejected without control or body changes',async t=>{
 const f=await fixture(t);await f.repository.mutateWorkspace(w=>{w.runs[f.runId].targetSnapshot=structuredClone(f.b);});await assert.rejects(()=>f.assignment.preview({recordId:f.recordId,destination:f.a}),{code:'legacy_dependency_conflict'});assert.equal(Object.keys((await f.control.read()).ownershipTransfers).length,0);
});
test('verified managed snapshots transfer with stable root identity and replay after main failure',async t=>{
 const f=await fixture(t,{managedSnapshot:true}),before=await f.repository.read(),file=Object.values(before.files)[0],p=await f.assignment.preview({recordId:f.recordId,destination:f.a});assert.ok(p.recordIds.includes(file.snapshotRecordId));f.failTransferMain();await assert.rejects(()=>f.assignment.move({...p,recordId:f.recordId,destination:f.a}));await f.assignment.recoverPending();const w=await f.repository.read(),snapshot=await f.repository.readRunSnapshot(f.runId);assert.equal(snapshot.recordId,file.snapshotRecordId);assert.equal(snapshot.ownerPackageId,f.a.packageId);assert.equal(snapshot.jobs[0].ownerPackageId,f.a.packageId);assert.equal(w.files[file.fileId].ownerPackageId,f.a.packageId);assert.equal(w.files[file.fileId].snapshotRecordId,file.snapshotRecordId);assert.equal((await f.control.read()).ownershipTransfers[file.snapshotRecordId].to,f.a.packageId);
});
test('prepared transfer into an expired target finishes only through maintenance recovery',async t=>{
 const f=await fixture(t),p=await f.assignment.preview({recordId:f.recordId,destination:f.a});f.failTransferMain();await assert.rejects(()=>f.assignment.move({...p,recordId:f.recordId,destination:f.a}));await f.trash.archive({packageId:f.a.packageId});f.clock.advance(72*3600*1000);await assert.rejects(()=>f.assignment.move({...p,recordId:f.recordId,destination:f.a}),{code:'package_expired'});const before=await f.repository.read(),intent=(await f.control.read()).ownershipTransfers[f.recordId];assert.throws(()=>applyOwnershipTransfer(structuredClone(before),intent,{now:f.clock.now()}),{code:'package_expired'});await f.assignment.recoverPending();assert.equal((await f.repository.read()).applications[f.applicationId].ownerPackageId,f.a.packageId);await assert.rejects(()=>f.jobs.getApplication(f.applicationId,f.a),{code:'package_expired'});
});
test('prepared snapshot transfer retired by target purge never revives legacy bodies on recovery',async t=>{
 const f=await fixture(t,{managedSnapshot:true}),p=await f.assignment.preview({recordId:f.recordId,destination:f.a});f.failTransferMain();await assert.rejects(()=>f.assignment.move({...p,recordId:f.recordId,destination:f.a}));await f.trash.archive({packageId:f.a.packageId});const purge=createPurgeService({repository:f.repository,trash:f.trash,fsAdapter:f.fsAdapter});assert.deepEqual((await purge.execute(await f.trash.preview({packageIds:[f.a.packageId]}))).completed,[f.a.packageId]);
 const recovered=await f.assignment.recoverPending();assert.equal(recovered.recovered,0);assert.equal(recovered.retired.length,1);assert.deepEqual(recovered.pending,[]);assert.equal((await f.control.read()).ownershipTransfers[f.recordId].phase,'prepared');assert.deepEqual(await f.assignment.list(),[]);const w=await f.repository.read();assert.equal(w.applications[f.applicationId],undefined);assert.equal(w.jobs[f.jobId],undefined);await assert.rejects(()=>fs.access(path.join(f.dataDir,'runs-v2',f.runId+'.json')),{code:'ENOENT'});
});
test('incomplete old deletion ledger keeps transfer pending and hides its private legacy summaries',async t=>{
 const f=await fixture(t),p=await f.assignment.preview({recordId:f.recordId,destination:f.a});f.failTransferMain();await assert.rejects(()=>f.assignment.move({...p,recordId:f.recordId,destination:f.a}));await f.trash.archive({packageId:f.a.packageId});await f.repository.withMaintenanceTransaction(async tx=>{const c=structuredClone(tx.control),pkg=tx.workspace.packages[f.a.packageId];c.deletionLedger[f.a.packageId]={phase:'purge_pending',recordIds:[],archiveId:pkg.archiveId,archivedAt:pkg.archivedAt,purgeAt:pkg.purgeAt};await tx.commitControl(c);});
 const result=await f.assignment.recoverPending();assert.equal(result.recovered,0);assert.deepEqual(result.retired,[]);assert.equal(result.pending[0].code,'ownership_transfer_pending');assert.equal((await f.control.read()).ownershipTransfers[f.recordId].phase,'prepared');assert.deepEqual(await f.assignment.list(),[]);
});
