import {isOwnSchool} from './common.mjs';
export const STANDARD_BUDGETS={maxSites:12,maxRequests:120,maxKeywords:6,maxPagesPerQuery:2,maxDetails:20};
export const BROAD_BUDGETS={...STANDARD_BUDGETS,maxSites:24,maxRequests:240};
export function buildCollectionPlan({targetSnapshot:target,profileRevision,catalog,health={},sourceOverrides={}}) {
 const defaults=target.coverageMode==='broad'?BROAD_BUDGETS:STANDARD_BUDGETS;const budgets={...defaults};for(const key of Object.keys(budgets))if(target.budgets?.[key]!=null)budgets[key]=Math.max(0,Math.min(budgets[key],target.budgets[key]));
 const profile=profileRevision?.profile||{};const cities=target.cityMode==='any'?[]:target.cityMode==='from_profile'?(profile.cities||profile.preferredCities||[]):target.cities||[];const keywords=[...new Set(target.roles||[])].slice(0,budgets.maxKeywords);const requested=(target.sourceIds||[]).map(id=>id==='searchApi'?'searchapi':id);const skipped=[],eligible=[];
 for(const site of catalog){const h=health[site.providerId+'/'+site.siteId];let reason=null;if(requested.length&&!requested.includes(site.providerId))reason='source_not_selected';else if(sourceOverrides[site.providerId]?.enabled===false)reason='disabled';else if(site.status!=='ready')reason=site.status;else if(h?.backoffUntil&&Date.parse(h.backoffUntil)>Date.now())reason='backoff';if(reason){skipped.push({sourceId:site.providerId,siteId:site.siteId,reason,explicit:(target.siteIds||[]).includes(site.siteId)});continue;}
 const explicit=(target.siteIds||[]).includes(site.siteId);const score=(explicit?100:0)+(isOwnSchool(site,profile)?40:0)+(site.regions?.some(r=>cities.includes(r))?20:0)+(site.majorFamilies?.some(f=>String(profile.major||'').includes(f))?10:0);eligible.push({site,score,explicit});}
 eligible.sort((a,b)=>b.score-a.score||a.site.siteId.localeCompare(b.site.siteId));const chosen=eligible.filter(x=>x.explicit).slice(0,budgets.maxSites);const groups=new Map();for(const e of eligible.filter(x=>!x.explicit)){if(!groups.has(e.site.category))groups.set(e.site.category,[]);groups.get(e.site.category).push(e);}
 while(chosen.length<budgets.maxSites&&[...groups.values()].some(g=>g.length))for(const entries of groups.values()){if(chosen.length>=budgets.maxSites)break;if(entries.length)chosen.push(entries.shift());}
 const ids=new Set(chosen.map(e=>e.site.siteId));for(const e of eligible)if(!ids.has(e.site.siteId))skipped.push({sourceId:e.site.providerId,siteId:e.site.siteId,reason:'site_budget_exhausted',explicit:e.explicit});for(const id of target.siteIds||[])if(!catalog.some(s=>s.siteId===id))skipped.push({siteId:id,reason:'unknown_site',explicit:true});
 const sites=chosen.map(e=>e.site),queries=sites.flatMap(site=>keywords.flatMap(keyword=>(cities.length?cities:['']).map(city=>({sourceId:site.providerId,siteId:site.siteId,keyword,city,pageLimit:budgets.maxPagesPerQuery}))));return {sites,queries,budgets,skipped};
}
